name: Extension CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python for local environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Run integration tests
        run: xvfb-run -a npm run test:e2e
        if: runner.os == 'Linux'
      - name: Run integration tests
        run: npm run test:e2e
        if: runner.os != 'Linux'
